-- NO-OP (intencional).
--
-- Este arquivo redefinia process_reengagement_followup com o cap anti-burst por clínica
-- (row_number particionado por clinic_id, teto de 5 por rodada).
--
-- Esse comportamento JÁ ESTÁ na migration 20260719000057_followup_wrongsend_guards, que é
-- numerada depois desta e é a definição canônica da função. A 057 tem, além do cap por clínica,
-- guardas que ESTA versão não tem: WhatsApp status='connected', send_blocked_until e o cap de
-- idade followup_max_idle_days. Manter a redefinição aqui faria um replay do zero terminar sem
-- essas guardas, porque a ordem de aplicação seguiria o número do arquivo.
--
-- Mantido como registro histórico. Nada a executar.
select 1;
