-- NO-OP (intencional).
--
-- Este arquivo redefinia process_forms_followup com o cap anti-burst por clínica
-- (row_number particionado por clinic_id, teto de 3 por rodada).
--
-- Esse comportamento JÁ ESTÁ na migration 20260719000057_followup_wrongsend_guards, que é
-- numerada depois desta e é a definição canônica da função (cap por clínica + guardas da
-- auditoria de envio errado). Manter a redefinição aqui faria um replay do zero terminar com
-- a versão SEM as guardas, porque a ordem de aplicação seguiria o número do arquivo.
--
-- Mantido como registro histórico. Nada a executar.
select 1;
