-- NO-OP (intencional). Registro histórico.
--
-- Este arquivo continha a PRIMEIRA versão da fonte única do predicado dos follow-ups
-- (fn_followup_candidates_* + os 4 motores + o preview). Ela foi integralmente substituída no
-- mesmo dia pela 20260721000022_followup_single_source_v2, depois de dois reviews acharem:
--   • quatro definições diferentes de "WhatsApp apto a enviar" dentro da própria fonte única,
--     sendo que a do pós não checava api_token e causava bloqueio de fila;
--   • janela de horário derivada com max() sobre as linhas candidatas, que virava o default 6-22
--     quando a fila estava vazia;
--   • join direto com whatsapp_instances, que duplicaria a linha em clínica multi-instância;
--   • api_token trafegando até o preview, que nunca precisou dele.
--
-- Manter a versão antiga aqui só criaria uma segunda descrição, mais detalhada e ERRADA, do mesmo
-- desenho. A definição canônica é a 022.
select 1;
